/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortifolioRouteImport } from './routes/portifolio'
import { Route as IndexRouteImport } from './routes/index'

const PortifolioRoute = PortifolioRouteImport.update({
  id: '/portifolio',
  path: '/portifolio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portifolio': typeof PortifolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portifolio': typeof PortifolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portifolio': typeof PortifolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/portifolio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/portifolio'
  id: '__root__' | '/' | '/portifolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortifolioRoute: typeof PortifolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portifolio': {
      id: '/portifolio'
      path: '/portifolio'
      fullPath: '/portifolio'
      preLoaderRoute: typeof PortifolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortifolioRoute: PortifolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
